# main.yml
name: kubectl test
on: push

jobs:
  build:
    name: kubectl
    runs-on: ubuntu-latest
    steps:
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
      id: setcontext
    - name: deploy
      run: kubectl get service
